[mfoldername, ~, ~] = fileparts(mfilename('fullpath'));

input_args = {...
    'input_foldername', fullfile(mfoldername, '..', 'data'), ...
    'input_filename', 'green_nature_waterfall.jpg', ...
    'stimulus_duration', 30.0, ... % sec
    'background_intensity', 0.1, ...
    'initial_adaptation_duration', 0.0, ... % sec
    'trial_adaptation_duration', 0.0, ... % sec
    'nb_repetitions', 25, ...
    'dmd_width', 1024, ... % px
    'dmd_height', 768, ... % px
    'dmd_frame_rate', 100.0, ... % Hz
    'dmd_inversed_polarity', false, ...
    'output_foldername', fullfile(pwd, 'outputs'), ...
};

natural_full_field(input_args);