[mfoldername, ~, ~] = fileparts(mfilename('fullpath'));

input_args = {...
    'input_foldername', fullfile(mfoldername, '..', 'data'), ...
    'input_filename', 'clips_stephanie_palmer.avi', ...
    'video_duration', 20.0, ... % sec
    'nb_movies', 1, ...
    'background_intensity', 0.1, ...
    'initial_adaptation_duration', 20.0, ... % sec
    'trial_adaptation_duration', 10.0, ... % sec
    'nb_repetitions', 25, ...
    'dmd_width', 1024, ... % px
    'dmd_height', 768, ... % px
    'dmd_frame_rate', 40.0, ... % Hz
    'dmd_inversed_polarity', false, ...
    'output_foldername', fullfile(pwd, 'outputs'), ...
};

natural_movies(input_args);