[mfoldername, ~, ~] = fileparts(mfilename('fullpath'));

input_args = {...
    'initial_adaptation_duration', 20.0, ... % sec
    'trial_adaptation_duration', 10.0, ... % sec
    'adaptation_intensity', 0.1, ...
    'background_intensity', 0.1, ...
    'd_ante', 0.5, ... % sec
    'step', {
        'd_ante', 1.5, ... % sec
        'd', 3.0, ... % sec
        'd_post', 3.0, ... % sec
    }, ...
    'freq_chirp', {
        'd_ante', 2.0, ... % sec
        'd', 8.0, ... % sec
        'd_post', 1.0, ... % sec
        'nb_periods', 32, ...
    }, ...
    'ampl_chirp', {
        'd_ante', 1.0, ... % sec
        'd', 8.0, ... % sec
        'd_post', 2.0, ... % sec
        'nb_periods', 16, ...
    }, ...
    'd_post', 2.0, ... % sec
    'nb_repetitions', 10, ...
    'dmd_width', 1024, ... % px
    'dmd_height', 768, ... % px
    'dmd_frame_rate', 60.0, ... % Hz
    'dmd_inversed_polarity', false, ...
    'output_foldername', fullfile(pwd, 'outputs'), ...
};

euler_full_field(input_args);
