[mfoldername, ~, ~] = fileparts(mfilename('fullpath'));

input_args = {...
    'background_intensity', 0.1, ...
    'nb_repetitions', 5 * 30, ...
    'dmd_width', 1024, ... % px
    'dmd_height', 768, ... % px
    'dmd_frame_rate', 60.0, ... % Hz
    'dmd_inversed_polarity', false, ...
    'output_foldername', fullfile(pwd, 'outputs'), ...
};

moving_bars(input_args);
